apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: threatintel-data-pvc
  namespace: threat-intelligence
spec:
  accessModes:
    - ReadWriteMany  # Allow multiple pods to access
  storageClassName: standard  # Adjust based on your cluster
  resources:
    requests:
      storage: 50Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data-pvc
  namespace: threat-intelligence
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data-pvc
  namespace: threat-intelligence
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
