name: "Validate JSON Schemas"
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate schemas
        run: |
          pip install jsonschema
          python -c '
          import json, jsonschema, sys
          all_valid = True
          for file in ["schemas/source.schema.json", "schemas/quality.schema.json"]:
              try:
                  print(f"Validating {file}...")
                  schema = json.load(open(file))
                  jsonschema.Draft7Validator.check_schema(schema)
                  print(f"{file} is valid.")
              except Exception as e:
                  print(f"Error validating {file}: {e}", file=sys.stderr)
                  all_valid = False
          if not all_valid:
              sys.exit(1)
          print("All schemas are valid.")
          '
