name: Build MkDocs Site

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/publish-docs.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This is needed for pushing to the repository
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material pymdown-extensions

      - name: Build MkDocs site
        run: mkdocs build --site-dir ./site

      - name: Copy files to docs directory for GitHub Pages
        run: |
          # Ensure docs directory exists (should already exist)
          mkdir -p docs

          # Create a .nojekyll file to disable Jekyll processing
          touch site/.nojekyll

          # Copy the built site to docs directory
          cp -r site/* docs/
          cp site/.nojekyll docs/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site       # The folder the action should deploy
          branch: gh-pages   # The branch the action should deploy to
          token: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically created token
